### ISSUE TITLE
Saved Image Hash

### ISSUE THREAD

**Issue by snowfro** [dacaldera/Hash_Import#2]
When pressing spacebar the image is saved but the corresponding hash does not match the projectonthmoon.com/b58.txt hash. Also when starting the sketch it momentarily shows a different image which is different every time it starts up so I think the old hashes that were being generated on the previous edition are still running in the background somehow.

**Comment by dacaldera** [comment]
Space-bar filename saving issue has been fixed. Startup image problem has also been fixed.
